[default.extend-words]
muc = "muc" # For Munich location code
Hashi = "Hashi"
HashiCorp = "HashiCorp"
mavrickrishi = "mavrick" # Username

[files]
extend-exclude = ["registry/coder/templates/aws-devcontainer/architecture.svg"] #False positive