[default.extend-words]
muc = "muc" # For Munich location code
Hashi = "Hashi"
HashiCorp = "HashiCorp"

[files]
extend-exclude = [
    "registry/coder/templates/aws-devcontainer/architecture.svg", #False positive
    "registry/mavrickrishi/README.md" # False positive - mavrickrishi is a username
]